This notebook is used to process data. From the original .tsv file, we try to extract the useful information and process the part of data for future use.

Based on aim of the project, we try to analyse the mobility of switzerland and some neighbor countries by twitter data. So from twitter we get, the useful information is the placeinformation, post time, text content.

Considered of the number of data, we divided the data into 4 part. The file shows the 1/4 data's process and we store the data processing result as .pickle file. The rest of data was processed by the seem method.

First, we delete the part of missing data and store the data into dataframe with column 'userId', 'createdAt','placeId','placeLatitude', 'placeLongitude','followersCount','friendsCount','statusesCount'.

Then we try to extract year, month, day, weekday, hour informtion from column 'createAt'. For this, we convert the data in colume 'createAt' into type of datatime, and add columns 'month', 'weekday', 'day', 'hour' respectively.
We store the time data as a file called 'twitter_create_time.pickle'.

Third, we store the place information: 'placeId', 'placeLatitude', 'placeLongitude' as file called 'geo_info.pickle'.

Another important process of data is about geography information. From the placeid, placeLatitude', 'placeLongitude', we can get information through the library 'geopy'. We extract the country_code, state respective to a specific placeid. Then we store the corresponding relation of 'placeid','country_code', 'state' as file called 'pId_geo_df'.

Besides, we store the users reletive information 'userId', 'followersCount', 'friendsCount' as file called 'user_info'.

Finally, we count number of twiiter on different time and different place.

In [1]:
import pandas as pd
import csv
import numpy as np
%load_ext autoreload
%autoreload 2

In [2]:
from geopy.geocoders import Nominatim
from geopy.distance import vincenty

# >>> from geopy.geocoders import Nominatim
# >>> geolocator = Nominatim()
# >>> location = geolocator.geocode("175 5th Avenue NYC")
# >>> print(location.address)
# Flatiron Building, 175, 5th Avenue, Flatiron, New York, NYC, New York, ...
# >>> print((location.latitude, location.longitude))
# (40.7410861, -73.9896297241625)
# >>> print(location.raw)
# {'place_id': '9167009604', 'type': 'attraction', ...}

def geo(loc):
    """ Input a string of loc"""
    geolocator = Nominatim()
    location = geolocator.geocode(loc)
    return location.longitude, location.latitude

def rev_geo(lon, lat):
    """Use geopy to do reverse geocoding
    
    Becarefule of the output format as geopy has multiple sources and can have many format.
    """
    geolocator = Nominatim()
    location = geolocator.reverse(str(lat) + ", " + str(lon))
    return location.raw

def distance(lon1, lat1, lon2, lat2):    
    newport_ri = (lon1, lat1)
    cleveland_oh = (lon1, lat2)
    return vincenty(newport_ri, cleveland_oh).kilometers

In [3]:
schema = pd.read_table("data/twitter-swisscom/schema.txt", header = None, delim_whitespace=True,index_col=0)

In [12]:
with open("data/twitter-swisscom/twex.tsv", 'r') as h:
    lines = h.readlines()
    
to_be_processed_lines = [i for k, i in enumerate(lines) if i.endswith('\\\n') ]

print(len(to_be_processed_lines))

2008290

In [20]:
def remove_line_breaks(list_of_strings):
    count = 0
    for i in range(len(list_of_strings)):
        list_of_strings[i] = list_of_strings[i].replace('\\\t', '')
        if list_of_strings[i].endswith('\\\n'):
            list_of_strings[i] = list_of_strings[i][:-2]
remove_line_breaks(lines)

In [398]:
with open("data/twitter-swisscom/modified_twex_first_5000000.tsv", 'w') as h:
    h.writelines(line[:5000000])

In [397]:
count = 0
reduced_line = []
for i in range(len(lines_modified)):
    if len(lines_modified[i].split('\t'))==20:
        reduced_line.append(lines_modified[i])
    if np.mod(i, 10000)==0:
        print(i)

0
10000
20000
30000
40000
50000
60000
70000
80000
90000
100000
110000
120000
130000
140000
150000
160000
170000
180000
190000
200000
210000
220000
230000
240000
250000
260000
270000
280000
290000
300000
310000
320000
330000
340000
350000
360000
370000
380000
390000
400000
410000
420000
430000
440000
450000
460000
470000
480000
490000
500000
510000
520000
530000
540000
550000
560000
570000
580000
590000
600000
610000
620000
630000
640000
650000
660000
670000
680000
690000
700000
710000
720000
730000
740000
750000
760000
770000
780000
790000
800000
810000
820000
830000
840000
850000
860000
870000
880000
890000
900000
910000
920000
930000
940000
950000
960000
970000
980000
990000
1000000
1010000
1020000
1030000
1040000
1050000
1060000
1070000
1080000
1090000
1100000
1110000
1120000
1130000
1140000
1150000
1160000
1170000
1180000
1190000
1200000
1210000
1220000
1230000
1240000
1250000
1260000
1270000
1280000
1290000
1300000
1310000
1320000
1330000
1340000
1350000
1360000
1370000
1380000
1390000
1400000
1410000
1420000
1430000
1440000
1450000
1460000
1470000
1480000
1490000
1500000
1510000
1520000
1530000
1540000
1550000
1560000
1570000
1580000
1590000
1600000
1610000
1620000
1630000
1640000
1650000
1660000
1670000
1680000
1690000
1700000
1710000
1720000
1730000
1740000
1750000
1760000
1770000
1780000
1790000
1800000
1810000
1820000
1830000
1840000
1850000
1860000
1870000
1880000
1890000
1900000
1910000
1920000
1930000
1940000
1950000
1960000
1970000
1980000
1990000
2000000
2010000
2020000
2030000
2040000
2050000
2060000
2070000
2080000
2090000
2100000
2110000
2120000
2130000
2140000
2150000
2160000
2170000
2180000
2190000
2200000
2210000
2220000
2230000
2240000
2250000
2260000
2270000
2280000
2290000
2300000
2310000
2320000
2330000
2340000
2350000
2360000
2370000
2380000
2390000
2400000
2410000
2420000
2430000
2440000
2450000
2460000
2470000
2480000
2490000
2500000
2510000
2520000
2530000
2540000
2550000
2560000
2570000
2580000
2590000
2600000
2610000
2620000
2630000
2640000
2650000
2660000
2670000
2680000
2690000
2700000
2710000
2720000
2730000
2740000
2750000
2760000
2770000
2780000
2790000
2800000
2810000
2820000
2830000
2840000
2850000
2860000
2870000
2880000
2890000
2900000
2910000
2920000
2930000
2940000
2950000
2960000
2970000
2980000
2990000
3000000
3010000
3020000
3030000
3040000
3050000
3060000
3070000
3080000
3090000
3100000
3110000
3120000
3130000
3140000
3150000
3160000
3170000
3180000
3190000
3200000
3210000
3220000
3230000
3240000
3250000
3260000
3270000
3280000
3290000
3300000
3310000
3320000
3330000
3340000
3350000
3360000
3370000
3380000
3390000
3400000
3410000
3420000
3430000
3440000
3450000
3460000
3470000
3480000
3490000
3500000
3510000
3520000
3530000
3540000
3550000
3560000
3570000
3580000
3590000
3600000
3610000
3620000
3630000
3640000
3650000
3660000
3670000
3680000
3690000
3700000
3710000
3720000
3730000
3740000
3750000
3760000
3770000
3780000
3790000
3800000
3810000
3820000
3830000
3840000
3850000
3860000
3870000
3880000
3890000
3900000
3910000
3920000
3930000
3940000
3950000
3960000
3970000
3980000
3990000
4000000
4010000
4020000
4030000
4040000
4050000
4060000
4070000
4080000
4090000
4100000
4110000
4120000
4130000
4140000
4150000
4160000
4170000
4180000
4190000
4200000
4210000
4220000
4230000
4240000
4250000
4260000
4270000
4280000
4290000
4300000
4310000
4320000
4330000
4340000
4350000
4360000
4370000
4380000
4390000
4400000
4410000
4420000
4430000
4440000
4450000
4460000
4470000
4480000
4490000
4500000
4510000
4520000
4530000
4540000
4550000
4560000
4570000
4580000
4590000
4600000
4610000
4620000
4630000
4640000
4650000
4660000
4670000
4680000
4690000
4700000
4710000
4720000
4730000
4740000
4750000
4760000
4770000
4780000
4790000
4800000
4810000
4820000
4830000
4840000
4850000
4860000
4870000
4880000
4890000
4900000
4910000
4920000
4930000
4940000
4950000
4960000
4970000
4980000
4990000
5000000
5010000
5020000
5030000
5040000
5050000
5060000
5070000
5080000
5090000
5100000
5110000
5120000
5130000
5140000
5150000
5160000
5170000
5180000
5190000
5200000
5210000
5220000
5230000
5240000
5250000
5260000
5270000
5280000
5290000
5300000
5310000
5320000
5330000
5340000
5350000
5360000
5370000
5380000
5390000
5400000
5410000
5420000
5430000
5440000
5450000
5460000
5470000
5480000
5490000
5500000
5510000
5520000
5530000
5540000
5550000
5560000
5570000
5580000
5590000
5600000
5610000
5620000
5630000
5640000
5650000
5660000
5670000
5680000
5690000
5700000
5710000
5720000
5730000
5740000
5750000
5760000
5770000
5780000
5790000
5800000
5810000
5820000
5830000
5840000
5850000
5860000
5870000
5880000
5890000
5900000
5910000
5920000
5930000
5940000
5950000
5960000
5970000
5980000
5990000
6000000
6010000
6020000
6030000
6040000
6050000
6060000
6070000
6080000
6090000
6100000
6110000
6120000
6130000
6140000
6150000
6160000
6170000
6180000
6190000
6200000
6210000
6220000
6230000
6240000
6250000
6260000
6270000
6280000
6290000
6300000
6310000
6320000
6330000
6340000
6350000
6360000
6370000
6380000
6390000
6400000
6410000
6420000
6430000
6440000
6450000
6460000
6470000
6480000
6490000
6500000
6510000
6520000
6530000
6540000
6550000
6560000
6570000
6580000
6590000
6600000
6610000
6620000
6630000
6640000
6650000
6660000
6670000
6680000
6690000
6700000
6710000
6720000
6730000
6740000
6750000
6760000
6770000
6780000
6790000
6800000
6810000
6820000
6830000
6840000
6850000
6860000
6870000
6880000
6890000
6900000
6910000
6920000
6930000
6940000
6950000
6960000
6970000
6980000
6990000
7000000
7010000
7020000
7030000
7040000
7050000
7060000
7070000
7080000
7090000
7100000
7110000
7120000
7130000
7140000
7150000
7160000
7170000
7180000
7190000
7200000
7210000
7220000
7230000
7240000
7250000
7260000
7270000
7280000
7290000
7300000
7310000
7320000
7330000
7340000
7350000
7360000
7370000
7380000
7390000
7400000
7410000
7420000
7430000
7440000
7450000
7460000
7470000
7480000
7490000
7500000
7510000
7520000
7530000
7540000
7550000
7560000
7570000
7580000
7590000
7600000
7610000
7620000
7630000
7640000
7650000
7660000
7670000
7680000
7690000
7700000
7710000
7720000
7730000
7740000
7750000
7760000
7770000
7780000
7790000
7800000
7810000
7820000
7830000
7840000
7850000
7860000
7870000
7880000
7890000
7900000
7910000
7920000
7930000
7940000
7950000
7960000
7970000
7980000
7990000
8000000
8010000
8020000
8030000
8040000
8050000
8060000
8070000
8080000
8090000
8100000
8110000
8120000
8130000
8140000
8150000
8160000
8170000
8180000
8190000
8200000
8210000
8220000
8230000
8240000
8250000
8260000
8270000
8280000
8290000
8300000
8310000
8320000
8330000
8340000
8350000
8360000
8370000
8380000
8390000
8400000
8410000
8420000
8430000
8440000
8450000
8460000
8470000
8480000
8490000
8500000
8510000
8520000
8530000
8540000
8550000
8560000
8570000
8580000
8590000
8600000
8610000
8620000
8630000
8640000
8650000
8660000
8670000
8680000
8690000
8700000
8710000
8720000
8730000
8740000
8750000
8760000
8770000
8780000
8790000
8800000
8810000
8820000
8830000
8840000
8850000
8860000
8870000
8880000
8890000
8900000
8910000
8920000
8930000
8940000
8950000
8960000
8970000
8980000
8990000
9000000
9010000
9020000
9030000
9040000
9050000
9060000
9070000
9080000
9090000
9100000
9110000
9120000
9130000
9140000
9150000
9160000
9170000
9180000
9190000
9200000
9210000
9220000
9230000
9240000
9250000
9260000
9270000
9280000
9290000
9300000
9310000
9320000
9330000
9340000
9350000
9360000
9370000
9380000
9390000
9400000
9410000
9420000
9430000
9440000
9450000
9460000
9470000
9480000
9490000
9500000
9510000
9520000
9530000
9540000
9550000
9560000
9570000
9580000
9590000
9600000
9610000
9620000
9630000
9640000
9650000
9660000
9670000
9680000
9690000
9700000
9710000
9720000
9730000
9740000
9750000
9760000
9770000
9780000
9790000
9800000
9810000
9820000
9830000
9840000
9850000
9860000
9870000
9880000
9890000
9900000
9910000
9920000
9930000
9940000
9950000
9960000
9970000
9980000
9990000
10000000
10010000
10020000
10030000
10040000
10050000
10060000
10070000
10080000
10090000
10100000
10110000
10120000
10130000
10140000
10150000
10160000
10170000
10180000
10190000
10200000
10210000
10220000
10230000
10240000
10250000
10260000
10270000
10280000
10290000
10300000
10310000
10320000
10330000
10340000
10350000
10360000
10370000
10380000
10390000
10400000
10410000
10420000
10430000
10440000
10450000
10460000
10470000
10480000
10490000
10500000
10510000
10520000
10530000
10540000
10550000
10560000
10570000
10580000
10590000
10600000
10610000
10620000
10630000
10640000
10650000
10660000
10670000
10680000
10690000
10700000
10710000
10720000
10730000
10740000
10750000
10760000
10770000
10780000
10790000
10800000
10810000
10820000
10830000
10840000
10850000
10860000
10870000
10880000
10890000
10900000
10910000
10920000
10930000
10940000
10950000
10960000
10970000
10980000
10990000
11000000
11010000
11020000
11030000
11040000
11050000
11060000
11070000
11080000
11090000
11100000
11110000
11120000
11130000
11140000
11150000
11160000
11170000
11180000
11190000
11200000
11210000
11220000
11230000
11240000
11250000
11260000
11270000
11280000
11290000
11300000
11310000
11320000
11330000
11340000
11350000
11360000
11370000
11380000
11390000
11400000
11410000
11420000
11430000
11440000
11450000
11460000
11470000
11480000
11490000
11500000
11510000
11520000
11530000
11540000
11550000
11560000
11570000
11580000
11590000
11600000
11610000
11620000
11630000
11640000
11650000
11660000
11670000
11680000
11690000
11700000
11710000
11720000
11730000
11740000
11750000
11760000
11770000
11780000
11790000
11800000
11810000
11820000
11830000
11840000
11850000
11860000
11870000
11880000
11890000
11900000
11910000
11920000
11930000
11940000
11950000
11960000
11970000
11980000
11990000
12000000
12010000
12020000
12030000
12040000
12050000
12060000
12070000
12080000
12090000
12100000
12110000
12120000
12130000
12140000
12150000
12160000
12170000
12180000
12190000
12200000
12210000
12220000
12230000
12240000
12250000
12260000
12270000
12280000
12290000
12300000
12310000
12320000
12330000
12340000
12350000
12360000
12370000
12380000
12390000
12400000
12410000
12420000
12430000
12440000
12450000
12460000
12470000
12480000
12490000
12500000
12510000
12520000
12530000
12540000
12550000
12560000
12570000
12580000
12590000
12600000
12610000
12620000
12630000
12640000
12650000
12660000
12670000
12680000
12690000
12700000
12710000
12720000
12730000
12740000
12750000
12760000
12770000
12780000
12790000
12800000
12810000
12820000
12830000
12840000
12850000
12860000
12870000
12880000
12890000
12900000
12910000
12920000
12930000
12940000
12950000
12960000
12970000
12980000
12990000
13000000
13010000
13020000
13030000
13040000
13050000
13060000
13070000
13080000
13090000
13100000
13110000
13120000
13130000
13140000
13150000
13160000
13170000
13180000
13190000
13200000
13210000
13220000
13230000
13240000
13250000
13260000
13270000
13280000
13290000
13300000
13310000
13320000
13330000
13340000
13350000
13360000
13370000
13380000
13390000
13400000
13410000
13420000
13430000
13440000
13450000
13460000
13470000
13480000
13490000
13500000
13510000
13520000
13530000
13540000
13550000
13560000
13570000
13580000
13590000
13600000
13610000
13620000
13630000
13640000
13650000
13660000
13670000
13680000
13690000
13700000
13710000
13720000
13730000
13740000
13750000
13760000
13770000
13780000
13790000
13800000
13810000
13820000
13830000
13840000
13850000
13860000
13870000
13880000
13890000
13900000
13910000
13920000
13930000
13940000
13950000
13960000
13970000
13980000
13990000
14000000
14010000
14020000
14030000
14040000
14050000
14060000
14070000
14080000
14090000
14100000
14110000
14120000
14130000
14140000
14150000
14160000
14170000
14180000
14190000
14200000
14210000
14220000
14230000
14240000
14250000
14260000
14270000
14280000
14290000
14300000
14310000
14320000
14330000
14340000
14350000
14360000
14370000
14380000
14390000
14400000
14410000
14420000
14430000
14440000
14450000
14460000
14470000
14480000
14490000
14500000
14510000
14520000
14530000
14540000
14550000
14560000
14570000
14580000
14590000
14600000
14610000
14620000
14630000
14640000
14650000
14660000
14670000
14680000
14690000
14700000
14710000
14720000
14730000
14740000
14750000
14760000
14770000
14780000
14790000
14800000
14810000
14820000
14830000
14840000
14850000
14860000
14870000
14880000
14890000
14900000
14910000
14920000
14930000
14940000
14950000
14960000
14970000
14980000
14990000
15000000
15010000
15020000
15030000
15040000
15050000
15060000
15070000
15080000
15090000
15100000
15110000
15120000
15130000
15140000
15150000
15160000
15170000
15180000
15190000
15200000
15210000
15220000
15230000
15240000
15250000
15260000
15270000
15280000
15290000
15300000
15310000
15320000
15330000
15340000
15350000
15360000
15370000
15380000
15390000
15400000
15410000
15420000
15430000
15440000
15450000
15460000
15470000
15480000
15490000
15500000
15510000
15520000
15530000
15540000
15550000
15560000
15570000
15580000
15590000
15600000
15610000
15620000
15630000
15640000
15650000
15660000
15670000
15680000
15690000
15700000
15710000
15720000
15730000
15740000
15750000
15760000
15770000
15780000
15790000
15800000
15810000
15820000
15830000
15840000
15850000
15860000
15870000
15880000
15890000
15900000
15910000
15920000
15930000
15940000
15950000
15960000
15970000
15980000
15990000
16000000
16010000
16020000
16030000
16040000
16050000
16060000
16070000
16080000
16090000
16100000
16110000
16120000
16130000
16140000
16150000
16160000
16170000
16180000
16190000
16200000
16210000
16220000
16230000
16240000
16250000
16260000
16270000
16280000
16290000
16300000
16310000
16320000
16330000
16340000
16350000
16360000
16370000
16380000
16390000
16400000
16410000
16420000
16430000
16440000
16450000
16460000
16470000
16480000
16490000
16500000
16510000
16520000
16530000
16540000
16550000
16560000
16570000
16580000
16590000
16600000
16610000
16620000
16630000
16640000
16650000
16660000
16670000
16680000
16690000
16700000
16710000
16720000
16730000
16740000
16750000
16760000
16770000
16780000
16790000
16800000
16810000
16820000
16830000
16840000
16850000
16860000
16870000
16880000
16890000
16900000
16910000
16920000
16930000
16940000
16950000
16960000
16970000
16980000
16990000
17000000
17010000
17020000
17030000
17040000
17050000
17060000
17070000
17080000
17090000
17100000
17110000
17120000
17130000
17140000
17150000
17160000
17170000
17180000
17190000
17200000
17210000
17220000
17230000
17240000
17250000
17260000
17270000
17280000
17290000
17300000
17310000
17320000
17330000
17340000
17350000
17360000
17370000
17380000
17390000
17400000
17410000
17420000
17430000
17440000
17450000
17460000
17470000
17480000
17490000
17500000
17510000
17520000
17530000
17540000
17550000
17560000
17570000
17580000
17590000
17600000
17610000
17620000
17630000
17640000
17650000
17660000
17670000
17680000
17690000
17700000
17710000
17720000
17730000
17740000
17750000
17760000
17770000
17780000
17790000
17800000
17810000
17820000
17830000
17840000
17850000
17860000
17870000
17880000
17890000
17900000
17910000
17920000
17930000
17940000
17950000
17960000
17970000
17980000
17990000
18000000
18010000
18020000
18030000
18040000
18050000
18060000
18070000
18080000
18090000
18100000
18110000
18120000
18130000
18140000
18150000
18160000
18170000
18180000
18190000
18200000
18210000
18220000
18230000
18240000
18250000
18260000
18270000
18280000
18290000
18300000
18310000
18320000
18330000
18340000
18350000
18360000
18370000
18380000
18390000
18400000
18410000
18420000
18430000
18440000
18450000
18460000
18470000
18480000
18490000
18500000
18510000
18520000
18530000
18540000
18550000
18560000
18570000
18580000
18590000
18600000
18610000
18620000
18630000
18640000
18650000
18660000
18670000
18680000
18690000
18700000
18710000
18720000
18730000
18740000
18750000
18760000
18770000
18780000
18790000
18800000
18810000
18820000
18830000
18840000
18850000
18860000
18870000
18880000
18890000
18900000
18910000
18920000
18930000
18940000
18950000
18960000
18970000
18980000
18990000
19000000
19010000
19020000
19030000
19040000
19050000
19060000
19070000
19080000
19090000
19100000
19110000
19120000
19130000
19140000
19150000
19160000
19170000
19180000
19190000
19200000
19210000
19220000
19230000
19240000
19250000
19260000
19270000
19280000
19290000
19300000
19310000
19320000
19330000
19340000
19350000
19360000
19370000
19380000
19390000
19400000
19410000
19420000
19430000
19440000
19450000
19460000
19470000
19480000
19490000
19500000
19510000
19520000
19530000
19540000
19550000
19560000
19570000
19580000
19590000
19600000
19610000
19620000
19630000
19640000
19650000
19660000
19670000
19680000
19690000
19700000
19710000
19720000
19730000
19740000
19750000
19760000
19770000
19780000
19790000
19800000
19810000
19820000
19830000
19840000
19850000
19860000
19870000
19880000
19890000
19900000
19910000
19920000
19930000
19940000
19950000
19960000
19970000
19980000
19990000
20000000
20010000
20020000
20030000
20040000
20050000
20060000
20070000
20080000
20090000
20100000
20110000
20120000
20130000
20140000
20150000
20160000
20170000
20180000
20190000
20200000
20210000

In [419]:
# None quating in the dataset
df = pd.read_csv("data/twitter-swisscom/modified_twex_first_5000000.tsv",
                 header = None, encoding = 'utf-8', sep='\t',quoting=csv.QUOTE_NONE)
df.columns = schema[1]
df.shape

/Users/lcav/anaconda/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(5000000, 20)

In [420]:
df_saved_3 = df[df.placeId != '\\N'][['userId', 'createdAt','placeId','placeLatitude', 'placeLongitude',
                                    'followersCount','friendsCount','statusesCount']]

In [421]:
df_saved_32 = df_saved_3[df_saved_3.createdAt!='0000-00-00 00:00:00']

In [422]:
df_saved3 = df_saved_32.copy()

In [423]:
import time

t = time.time()
df_saved3['time'] = df_saved3['createdAt'].apply(lambda x: pd.Timestamp(x).to_pydatetime())
print("500000 entries takes %i secs" % (time.time() - t))

500000 entries takes 14 secs

In [424]:
t = time.time()
df_saved3['weekday'] = df_saved3['time'].apply(lambda x: x.weekday())
print("500000 entries takes %i secs" % (time.time() - t))

500000 entries takes 43 secs

In [425]:
t1 = time.time()
df_saved3['day'] = df_saved3['time'].apply(lambda x: x.day)
print("500000 entries takes %i secs" % (time.time() - t1))

500000 entries takes 31 secs

In [426]:
t2 = time.time()
df_saved3['hour'] = df_saved3['time'].apply(lambda x: x.hour)
print("500000 entries takes %i secs" % (time.time() - t2))

500000 entries takes 21 secs

In [427]:
t3 = time.time()
df_saved3['month'] = df_saved3['time'].apply(lambda x: x.month)
print("500000 entries takes %i secs" % (time.time() - t3))

500000 entries takes 30 secs

In [144]:
df_saved3[['time', 'month', 'weekday', 'day', 'hour']].head(5)

1                time  month  weekday  day  hour
0 2013-04-24 01:42:07      4        2   24     1
1 2013-04-24 01:42:39      4        2   24     1
2 2013-04-24 01:42:44      4        2   24     1
3 2013-04-24 01:43:01      4        2   24     1
4 2013-04-24 01:44:13      4        2   24     1

In [428]:
twitter_create_time = df_saved3[['userId', 'createdAt', 'placeId', 'weekday', 'day', 'hour', 'month']]

In [429]:
with open('data/twitter-swisscom/twitter_create_time_1.pickle','wb') as t:
    pickle.dump(twitter_create_time,t)

In [430]:
geo_info_1 = df_saved3[['placeId', 'placeLatitude', 'placeLongitude']].groupby(['placeId']).first().reset_index()

In [431]:
with open('data/twitter-swisscom/geo_info_1.pickle','wb') as g:
    pickle.dump(geo_info_1,g)

In [434]:
user_count_1 = df_saved1[['userId', 'followersCount', 'friendsCount']].groupby(['userId']).first().reset_index()

In [435]:
with open('data/twitter-swisscom/user_info_1.pickle','wb') as u:
    pickle.dump(user_count_1,u)

In [29]:
import pickle
import os

if os.path.exists("data/twitter-swisscom/placeId_lat_lon_df.pickle"):
    with open("data/twitter-swisscom/placeId_lat_lon_df.pickle", "rb") as h:
        placeId_lat_lon_df = pickle.load(h)
else:
    def get_geo_info(x):
        return rev_geo(lon=x['placeLongitude'], lat=x['placeLatitude'])

    import time
    t = time.time()
    placeId_lat_lon_df['raw_geo'] = placeId_lat_lon_df.apply(lambda x: get_geo_info(x), axis=1)
    print("time for all items = ", time.time() - t)
    with open("data/twitter-swisscom/placeId_lat_lon_df.pickle", "wb") as h:
        pickle.dump(placeId_lat_lon_df, h)

In [14]:
df1 = df_saved3.groupby("placeId").first()

In [16]:
new_geo_list = [i for i in df1.index if i not in placeId_lat_lon_df.index]

In [25]:
df1.loc[new_geo_list]

1,userId,createdAt,placeLatitude,placeLongitude,followersCount,friendsCount,statusesCount,time,weekday,day,hour,month
placeId,,,,,,,,,,,,
0013241b7342de79,17044332,2013-05-25 10:07:56,47.0462,8.30735,260,190,5112,2013-05-25 10:07:56,5,25,10,5
002c56c5c8e4dbd1,1182255084,2013-04-28 20:36:24,47.1401,8.1911,11,25,21,2013-04-28 20:36:24,6,28,20,4
003145e292845154,897235303,2013-06-02 01:19:55,47.6678,6.46952,54,93,683,2013-06-02 01:19:55,6,2,1,6
004406987153f5fd,910949312,2014-03-03 10:28:07,46.7772,6.69034,115,116,905,2014-03-03 10:28:07,0,3,10,3
00466891f6f1cb75,1158317665,2013-05-29 04:21:44,46.3786,8.07874,94,309,92,2013-05-29 04:21:44,2,29,4,5
004d7579a2c007f1,43680662,2013-04-29 11:08:16,46.9937,6.93763,669,593,11850,2013-04-29 11:08:16,0,29,11,4
0051dfd3a6dc6135,1140785258,2013-05-05 18:06:45,47.4669,8.57225,178,808,2547,2013-05-05 18:06:45,6,5,18,5
00591b652de4e0e2,272908164,2013-05-18 12:31:14,47.3683,8.54505,307,299,2979,2013-05-18 12:31:14,5,18,12,5
0071a18012293f9a,51062550,2013-06-20 15:37:59,46.4989,9.84635,158,277,4515,2013-06-20 15:37:59,3,20,15,6
0088119e2ba901d3,352322537,2013-05-04 13:52:58,46.2841,6.04735,610,458,23218,2013-05-04 13:52:58,5,4,13,5
008af5ca52d11103,171431916,2013-05-12 10:53:28,46.7883,6.62222,3154,179,94893,2013-05-12 10:53:28,6,12,10,5
00a978ecf14972da,121049123,2013-12-05 12:34:02,46.0371,8.19955,146303,1,18147,2013-12-05 12:34:02,3,5,12,12
00ace7159f56be12,366858633,2013-04-24 19:02:21,47.2738,8.3351,163,164,5392,2013-04-24 19:02:21,2,24,19,4
00ad6eddf1f8a93a,401513069,2013-04-26 05:57:42,45.9302,8.71964,75,116,1100,2013-04-26 05:57:42,4,26,5,4
00b28f9f7d3db2e7,432906978,2013-04-28 09:59:58,47.2,6.26799,603,270,76643,2013-04-28 09:59:58,6,28,9,4
00c41f17a1e0a135,24662186,2013-05-01 07:22:29,47.1794,7.30329,2439,2415,11170,2013-05-01 07:22:29,2,1,7,5
00c4722104ba3ada,54804811,2013-06-15 09:45:15,47.3222,5.98869,339,380,22849,2013-06-15 09:45:15,5,15,9,6
00c51558ba93e821,749006551,2013-04-25 11:33:05,46.9322,6.36497,13,55,222,2013-04-25 11:33:05,3,25,11,4
00cb14cda15c7f72,315078638,2013-05-04 12:23:48,47.0517,8.60999,983,690,24374,2013-05-04 12:23:48,5,4,12,5
00d5e1273425dbfd,351146540,2013-05-06 21:35:41,47.643,8.12689,556,26,176,2013-05-06 21:35:41,0,6,21,5
00d8025f5d8239d7,144520174,2013-05-17 18:21:08,46.4622,10.3631,117,265,1148,2013-05-17 18:21:08,4,17,18,5
00d9f6e2070b58c6,717779802,2013-05-17 06:51:35,47.6345,6.56606,34,54,86,2013-05-17 06:51:35,4,17,6,5
00db800fad3e5eed,13250122,2013-04-28 07:58:43,45.9106,9.21812,527,2071,7371,2013-04-28 07:58:43,6,28,7,4
00de37b60c7a0189,958506427,2013-06-02 08:40:23,46.3405,6.88195,229,167,10795,2013-06-02 08:40:23,6,2,8,6
00fd19ed0a148307,552258801,2013-05-09 10:18:24,46.7205,6.4308,286,136,25540,2013-05-09 10:18:24,3,9,10,5
0101cea449c72f80,1108408874,2013-04-24 16:28:32,46.2712,6.39631,76,127,159,2013-04-24 16:28:32,2,24,16,4
010c81979f758f2f,596686298,2013-04-27 19:53:45,45.9271,5.93292,59,255,96,2013-04-27 19:53:45,5,27,19,4
0110adcf67b7cd1e,439626079,2013-04-24 23:31:59,45.8554,6.75509,29520,289,60206,2013-04-24 23:31:59,2,24,23,4
011962c31dcf3201,187449687,2013-05-03 17:40:37,46.9864,9.54264,22,76,17,2013-05-03 17:40:37,4,3,17,5
013e2851679004b4,349003497,2013-05-01 20:15:09,46.823,8.40204,33,64,207,2013-05-01 20:15:09,2,1,20,5
...,...,...,...,...,...,...,...,...,...,...,...,...
ff16cf8e93248754,498155884,2013-05-19 19:17:39,46.3887,6.77716,841,1520,5472,2013-05-19 19:17:39,6,19,19,5
ff3ab3894b185105,512287282,2014-01-26 11:40:42,47.5196,7.45654,50,8,15956,2014-01-26 11:40:42,6,26,11,1
ff4f4237c9941832,1417894700,2013-05-10 19:07:44,47.1355,7.92475,1,22,37,2013-05-10 19:07:44,4,10,19,5
ff55a18272d5f5ed,49806346,2013-05-26 20:39:05,47.4352,7.17004,541,437,24839,2013-05-26 20:39:05,6,26,20,5
ff57f769001e3417,133347470,2013-10-03 18:47:00,47.2871,8.08811,118,144,991,2013-10-03 18:47:00,3,3,18,10
ff5fa4e98d4d40bf,117208880,2013-05-11 12:04:53,47.5616,7.59405,3563,1284,17295,2013-05-11 12:04:53,5,11,12,5
ff5ff486cb027b63,309873878,2013-05-03 19:54:00,46.8539,6.729,254,1031,7095,2013-05-03 19:54:00,4,3,19,5
ff67fc591834b372,266001803,2013-05-25 11:23:00,45.8724,10.1546,1637,1454,9985,2013-05-25 11:23:00,5,25,11,5
ff738bd11c6a9031,441279425,2013-04-25 15:22:26,45.9698,8.97069,80,519,2385,2013-04-25 15:22:26,3,25,15,4
ff759aab84f022ee,557890880,2013-06-01 05:39:58,47.5526,7.37806,1748,1434,41974,2013-06-01 05:39:58,5,1,5,6
ff75df76c35b939b,225917232,2013-05-23 21:52:11,47.1489,7.61544,14637,107,9717,2013-05-23 21:52:11,3,23,21,5
ff7a7734cac827a4,1256580931,2013-04-24 19:51:23,46.9443,9.49866,60,53,465,2013-04-24 19:51:23,2,24,19,4
ff8ee52edf03e6bd,11479942,2013-04-24 19:46:05,46.0509,9.19546,531,1025,15940,2013-04-24 19:46:05,2,24,19,4
ff9d79bf32ff358f,423242556,2013-06-08 05:50:21,47.1012,6.35216,82,231,189,2013-06-08 05:50:21,5,8,5,6
ff9e7284eacac888,791817955,2013-05-01 17:42:43,47.1389,7.24955,316,749,1685,2013-05-01 17:42:43,2,1,17,5
ffa2666592b97060,55518076,2013-04-27 09:50:16,47.4199,8.50859,1150,450,86487,2013-04-27 09:50:16,5,27,9,4
ffa4ff06c4fc16fb,390285148,2013-04-24 19:46:08,46.8959,7.13662,105,473,668,2013-04-24 19:46:08,2,24,19,4
ffabde319eab7a59,759118,2013-06-02 15:14:59,46.4977,6.38887,179,160,27196,2013-06-02 15:14:59,6,2,15,6
ffaead032ce0bb92,17994798,2013-04-26 10:47:36,45.788,7.42454,161,37,3366,2013-04-26 10:47:36,4,26,10,4
ffbb850667c44fb1,1207077908,2013-12-14 20:56:14,47.1344,6.46347,314,245,6924,2013-12-14 20:56:14,5,14,20,12
ffc80c030bb1475b,15484085,2013-05-10 09:06:52,46.8085,8.7076,62,151,622,2013-05-10 09:06:52,4,10,9,5
ffcbc3a6f012fab3,617204255,2013-05-04 14:13:36,45.7795,6.1065,326,310,23306,2013-05-04 14:13:36,5,4,14,5
ffcdf08657f735fe,1359577082,2013-05-08 06:02:19,47.4587,8.43892,9,38,63,2013-05-08 06:02:19,2,8,6,5
ffd18549471cfdb9,79446174,2013-05-17 21:53:59,45.8177,8.82771,39,126,66,2013-05-17 21:53:59,4,17,21,5
ffe349453031b9b4,473830170,2013-04-29 05:46:03,46.0672,7.03052,62,131,739,2013-04-29 05:46:03,0,29,5,4
ffe3eaf96f78d614,302105698,2013-06-22 17:42:21,47.407,8.38711,185,251,6757,2013-06-22 17:42:21,5,22,17,6
ffe479331c6c7d55,188348534,2013-05-08 10:51:26,46.5224,6.6261,361,189,13157,2013-05-08 10:51:26,2,8,10,5
ffe77b2e978b0512,1252081350,2013-05-24 10:31:45,47.0329,9.70894,0,11,5,2013-05-24 10:31:45,4,24,10,5
ffea095f6cf7b944,52016531,2013-04-24 21:28:33,47.0913,7.16726,592,859,20355,2013-04-24 21:28:33,2,24,21,4
ffef96a3aaffd41e,71528370,2013-04-29 07:03:35,47.7146,8.9421,4613,4259,519122,2013-04-29 07:03:35,0,29,7,4

In [123]:
def get_place_name_of_placeId_from_df(df, pause_secs=1):
    """The input dataframe is """
    import time
    if (df.index.name != 'placeId' or any(df.index != df.index.unique())):
        raise ValueError("Input dataframe should use uniuqe 'placeId' as index")

    for col in ['placeLongitude', 'placeLatitude']:
        if (col not in df.columns):
            raise ValueError("Input dataframe should have cols 'placeLongitude', 'placeLatitude'")

    pId_geo_map = []
    t = time.time()
    try:
        for i, pId in enumerate(df.index):
            x = df.loc[pId]
            raw_geo_data = rev_geo(lon=x['placeLongitude'], lat=x['placeLatitude'])
            pId_geo_map.append((pId, raw_geo_data))
            time.sleep(pause_secs)
            print(i, time.time() - t)
            t = time.time()
    except Exception as e:
        print("Expected Error " + e)
        return pId_geo_map

    return pId_geo_map

In [20]:
#if os.path.exists('data/twitter-swisscom/pId_geo_df_1.pickle'):
#    with open("data/twitter-swisscom/pId_geo_df_1.pickle", 'rb') as d:
#        pId_geo_df_1 = pickle.load(d)
# else:
#    list_of_pId_geo_pair = get_place_name_of_placeId_from_df(place_df_1, pause_secs=1.1)
#    pId_geo_map={'placeId':[i for i,geo in results], 'geo':[geo for i,geo in results]}
#    pId_geo_df_1 = pd.DataFrame(pId_geo_map).set_index('placeId')
#    with open("data/twitter-swisscom/pId_geo_df_1.pickle", 'wb') as d:
#        pickle.dump(pId_geo_df_1, d)

In [303]:
with open('data/twitter-swisscom/pId_geo_df_1.pickle', 'rb') as f:
    tmp1 = pickle.load(f)
    tmp1 = tmp1[['geo']]
    tmp_list=[tmp1]
for i in range(1,4):
    i=str(i)
    with open('data/twitter-swisscom/pId_geo_df_2_'+i+'_3.pickle', 'rb') as f:
        tmp2 = pickle.load(f)
        tmp_list.append(tmp2)
with open('data/twitter-swisscom/pId_geo_df_3.pickle','rb') as ff:
    tmp3 = pickle.load(ff)
    tmp_list.append(tmp3)
with open('data/twitter-swisscom/pId_geo_df_4.pickle','rb') as fff:
    tmp4 = pickle.load(fff)
    tmp_list.append(tmp4)
pId_geo_df = pd.concat(tmp_list)

In [304]:
pId_geo_df = pId_geo_df.reset_index().groupby('placeId').first()

In [306]:
pId_geo_df=pId_geo_df[pId_geo_df['geo']!={'error': 'Unable to geocode'}]

In [307]:
state_list=[]
countrycode_list=[]
for i in range(pId_geo_df.shape[0]):
    countrycode_list.append(pId_geo_df.iloc[i,0]['address'].get('country_code','inaccessable'))
    state_list.append(pId_geo_df.iloc[i,0]['address'].get('state','inaccessable'))

In [308]:
pId_geo_df['country_code']=countrycode_list
pId_geo_df['state']=state_list

In [310]:
pId_geo_df1=pId_geo_df[pId_geo_df['state']!='inaccessable']
pId_geo_df2=pId_geo_df1[pId_geo_df1['country_code']!='inaccessable']

In [146]:
pId_part_2 = df_saved4.placeId.unique()

In [147]:
def get_additional_pId(processed_pId, candidate_pId):
    return [i for i in processed_pId if i not in candidate_pId]

In [148]:
to_be_processed_pId = get_additional_pId(pId_part_2,pId_geo_df.index)

In [149]:
to_be_processed_pId_df=df_saved4[df_saved4['placeId'].isin(to_be_processed_pId)]

In [150]:
to_be_processed_pId_df = to_be_processed_pId_df.groupby('placeId').first()

In [151]:
to_be_processed_pId_df=to_be_processed_pId_df[to_be_processed_pId_df['placeLatitude']!=r'\N']

In [152]:
processed_pId = get_place_name_of_placeId_from_df(to_be_processed_pId_df, pause_secs=1)

In [153]:
pId_geo_map={'placeId':[i for i,geo in processed_pId], 'geo':[geo for i,geo in processed_pId]}
pId_geo_df_2 = pd.DataFrame(pId_geo_map).set_index('placeId')
with open("data/twitter-swisscom/pId_geo_df_4.pickle", 'wb') as d:
    pickle.dump(pId_geo_df_2, d)

### read placeId

In [3]:
import pickle
import os
with open("data/twitter-swisscom/pId_geo_df_total.pickle", "rb") as h:
    pId_geo_df_1 = pickle.load(h)

In [5]:
pId_geo_df_1.shape

(14908, 3)

In [72]:
with open("data/twitter-swisscom/df_saved3.pickle", "rb") as h:
    df_saved3 = pickle.load(h)

In [73]:
df_saved3.head()

1,userId,createdAt,placeId,placeLatitude,placeLongitude,followersCount,friendsCount,statusesCount,time,weekday,day,hour,month
552,6257282,2010-03-09 18:09:51,9f61955efec1f923,47.5367,7.57849,14249,9260,19585,2010-03-09 18:09:51,1,9,18,3
610,15602037,2010-03-10 22:44:24,0f62dd0accad77d3,47.3791,8.50021,177,136,5167,2010-03-10 22:44:24,2,10,22,3
612,625553,2010-03-11 05:59:25,f0df77ae625fea91,46.1996,6.13011,471,82,3363,2010-03-11 05:59:25,3,11,5,3
613,17341045,2010-03-11 06:18:47,512441eea623380b,46.9214,7.38855,586,508,9016,2010-03-11 06:18:47,3,11,6,3
619,634553,2010-03-11 07:03:10,234fc23432bfd559,46.1938,6.15415,2230,387,10605,2010-03-11 07:03:10,3,11,7,3

In [18]:
transferred = df_saved3.groupby(['placeId','year','month','day']).count()['userId']

In [23]:
transferred.name = 'twittwer_count'

In [26]:
trans = transferred.reset_index()
trans

                 placeId  year  month  day  twittwer_count
0       000a93ad12003aaa  2010     10    4               1
1       000a93ad12003aaa  2010     11   28               1
2       000a93ad12003aaa  2010     12    7               1
3       000a93ad12003aaa  2011      1   26               1
4       000a93ad12003aaa  2011      1   27               2
5       000a93ad12003aaa  2011      2    2               1
6       000a93ad12003aaa  2011      3    1               1
7       000a93ad12003aaa  2011      3   24               1
8       000a93ad12003aaa  2011      4    1               1
9       000a93ad12003aaa  2011      4   10               1
10      000a93ad12003aaa  2011      4   16               1
11      000a93ad12003aaa  2011      4   17               2
12      000a93ad12003aaa  2011      5    2               4
13      000a93ad12003aaa  2011      5    5               1
14      000a93ad12003aaa  2011      5   13               2
15      000a93ad12003aaa  2011      5   17               3
16      000a93ad12003aaa  2011      5   18               3
17      000a93ad12003aaa  2011      5   20               5
18      000a93ad12003aaa  2011      5   25               6
19      000a93ad12003aaa  2011      5   26               1
20      000a93ad12003aaa  2011      6    5               2
21      000a93ad12003aaa  2011      6   15               1
22      000a93ad12003aaa  2011      6   16               3
23      000a93ad12003aaa  2011      6   18               2
24      000a93ad12003aaa  2011      6   19               1
25      000a93ad12003aaa  2011      7    5               1
26      000a93ad12003aaa  2011      8   13               1
27      000a93ad12003aaa  2011     10    2               1
28      000a93ad12003aaa  2011     10    6               1
29      000a93ad12003aaa  2011     10   16               2
...                  ...   ...    ...  ...             ...
444119  ffef96a3aaffd41e  2012      9    1               1
444120  ffef96a3aaffd41e  2012      9   18               1
444121  ffef96a3aaffd41e  2012      9   23               1
444122  ffef96a3aaffd41e  2012      9   24               1
444123  ffef96a3aaffd41e  2012     10    7               1
444124  ffef96a3aaffd41e  2012     10   18               1
444125  ffef96a3aaffd41e  2012     10   22               1
444126  ffef96a3aaffd41e  2012     10   28               1
444127  ffef96a3aaffd41e  2012     11    1               1
444128  ffef96a3aaffd41e  2012     11    2               1
444129  ffef96a3aaffd41e  2012     11    5               1
444130  ffef96a3aaffd41e  2012     11    6               1
444131  ffef96a3aaffd41e  2012     11   16               1
444132  ffef96a3aaffd41e  2012     11   22               1
444133  ffef96a3aaffd41e  2012     12   30               1
444134  ffef96a3aaffd41e  2013      1   10               1
444135  ffef96a3aaffd41e  2013      1   13               1
444136  ffef96a3aaffd41e  2013      1   26               1
444137  ffef96a3aaffd41e  2013      2   10               1
444138  ffef96a3aaffd41e  2013      2   11               1
444139  ffef96a3aaffd41e  2013      2   17               1
444140  ffef96a3aaffd41e  2013      3   10               1
444141  ffef96a3aaffd41e  2013      3   14               1
444142  ffef96a3aaffd41e  2013      3   18               1
444143  ffef96a3aaffd41e  2013      4    3               1
444144  ffef96a3aaffd41e  2013      4    7               1
444145  ffef96a3aaffd41e  2013      4   13               1
444146  ffef96a3aaffd41e  2013      4   19               1
444147  ffef96a3aaffd41e  2013      4   21               1
444148  ffefc7ae43d6198b  2010     10   19               1

[444149 rows x 5 columns]

In [75]:
trans2 = trans.join(pId_geo_df_1[['country_code', 'state']], on='placeId')

In [83]:
trans2 = trans2[haha2.state != 'unspecified']

In [84]:
aimed_table = haha2.pivot_table( columns=['year','month','day'],index =['country_code', 'state'], values='twittwer_count', fill_value = 0, aggfunc= 'sum')

In [85]:
aimed_table.head()

year                                1994                1995    1996    ...  \
month                                 3  4  5  8  10 12   12      6     ...
day                                   16 4  26 2  20 7    25 30   18 26 ...
country_code state                                                      ...
at           Tirol                     0  0  0  0  0  0    0  0    0  0 ...
             Vorarlberg                0  0  0  0  0  0    0  0    0  0 ...
ch           Aargau                    0  0  0  0  0  0    0  0    0  0 ...
             Appenzell Ausserrhoden    0  0  0  0  0  0    0  0    0  0 ...
             Appenzell Innerrhoden     0  0  0  0  0  0    0  0    0  0 ...

year                                2013                                     \
month                                 4
day                                   15   16   17   18   19   20   21   22
country_code state
at           Tirol                     7    4    3    1    4    4    1    1
             Vorarlberg              156   97  117  142  204  191  186  157
ch           Aargau                  147  145  187  146  102  244  268  229
             Appenzell Ausserrhoden    6    4   60   69   81   30   16   17
             Appenzell Innerrhoden     1    1    5    0    0    5    3    9

year
month
day                                   23 24
country_code state
at           Tirol                     1  0
             Vorarlberg              159  1
ch           Aargau                  226  7
             Appenzell Ausserrhoden    9  0
             Appenzell Innerrhoden    15  0

[5 rows x 1169 columns]

In [86]:
haha2[(haha2.day == 15) & (haha2.year==2013)&(haha2.month==4) & (haha2.country_code=='at')].groupby('state').sum()

             year  month  day  twittwer_count
state
Tirol        2013      4   15               7
Vorarlberg  44286     88  330             156

In [98]:
tmp_list = []
year_list = [2010, 2011, 2012, 2013]
for year in year_list:
    tmp_table = aimed_table[year]
    tmp_list.append(tmp_table.apply(lambda x: x.sum(), axis=1))

geo_x_year_df = pd.concat(tmp_list, axis=1 )
geo_x_year_df.columns=year_list

In [102]:
geo_x_year_df.head()

                                     2010  2011   2012   2013
country_code state
at           Tirol                     14    47   2832   5915
             Vorarlberg               119  1247  28816  15685
ch           Aargau                   392  2754  49473  23069
             Appenzell Ausserrhoden    11   147   2718   1083
             Appenzell Innerrhoden      1    68   1844    359